library(plyr)

# BEGINNING OF THE DISS PROJECT -- ECLSB DATA

# 9/12/16

setwd('~/Dropbox/PhD/Diss/Analyses/ECLS-B/')

# STEP 1: READ IN THE DATA

y2001 <- read.table('./TRIM_Avg/microdata_7i5.dat', header=T)
y2002 <- read.table('./TRIM_Avg/microdata_tc9.dat', header=T)
y2003 <- read.table('./TRIM_Avg/microdata_vsa.dat', header=T)
y2004 <- read.table('./TRIM_Avg/microdata_h6u.dat', header=T)
y2005 <- read.table('./TRIM_Avg/microdata_mko.dat', header=T)
y2006 <- read.table('./TRIM_Avg/microdata_v7t.dat', header=T)
y2007 <- read.table('./TRIM_Avg/microdata_r4o.dat', header=T)
y2008 <- read.table('./TRIM_Avg/microdata_8qe.dat', header=T)


y2001$YEAR <- 2001
y2002$YEAR <- 2002
y2003$YEAR <- 2003
y2004$YEAR <- 2004
y2005$YEAR <- 2005
y2006$YEAR <- 2006
y2007$YEAR <- 2007
y2008$YEAR <- 2008

y2001 <- y2001[y2001$NUMBERDEPKIDS>0,]
y2002 <- y2002[y2002$NUMBERDEPKIDS>0,]
y2003 <- y2003[y2003$NUMBERDEPKIDS>0,]
y2004 <- y2004[y2004$NUMBERDEPKIDS>0,]
y2005 <- y2005[y2005$NUMBERDEPKIDS>0,]
y2006 <- y2006[y2006$NUMBERDEPKIDS>0,]
y2007 <- y2007[y2007$NUMBERDEPKIDS>0,]
y2008 <- y2008[y2008$NUMBERDEPKIDS>0,]


y2001 <- y2001[y2001$FAMILYREFERENCERELATION==1,]
y2002 <- y2002[y2002$FAMILYREFERENCERELATION==1,]
y2003 <- y2003[y2003$FAMILYREFERENCERELATION==1,]
y2004 <- y2004[y2004$FAMILYREFERENCERELATION==1,]
y2005 <- y2005[y2005$FAMILYREFERENCERELATION==1,]
y2006 <- y2006[y2006$FAMILYREFERENCERELATION==1,]
y2007 <- y2007[y2007$FAMILYREFERENCERELATION==1,]
y2008 <- y2008[y2008$FAMILYREFERENCERELATION==1,]

y2001$NUMBERDEPKIDS[y2001$NUMBERDEPKIDS>4] <- 4
y2002$NUMBERDEPKIDS[y2002$NUMBERDEPKIDS>4] <- 4
y2003$NUMBERDEPKIDS[y2003$NUMBERDEPKIDS>4] <- 4
y2004$NUMBERDEPKIDS[y2004$NUMBERDEPKIDS>4] <- 4
y2005$NUMBERDEPKIDS[y2005$NUMBERDEPKIDS>4] <- 4
y2006$NUMBERDEPKIDS[y2006$NUMBERDEPKIDS>4] <- 4
y2007$NUMBERDEPKIDS[y2007$NUMBERDEPKIDS>4] <- 4
y2008$NUMBERDEPKIDS[y2008$NUMBERDEPKIDS>4] <- 4


y2001AVG <- ddply(y2001, .(FIPSSTATECODE, NUMBERDEPKIDS), summarise, EITC = mean(EARNEDINCOMETAXCREDIT, na.rm=T), CTC = mean(CHILDTAXCREDIT, na.rm=T), 
                      ACDC = mean(ADDITIONALCHILDTAXCREDIT, na.rm=T), ANNUALBENEFITSRECEIVED = mean(ANNUALBENEFITSRECEIVED, na.rm=T),
                      ANNUALBENEFITSELIGIBLEFOR = mean(ANNUALBENEFITSELIGIBLEFOR, na.rm=T), YEAR = unique(YEAR))

y2002AVG <- ddply(y2002, .(FIPSSTATECODE, NUMBERDEPKIDS), summarise, EITC = mean(EARNEDINCOMETAXCREDIT, na.rm=T), CTC = mean(CHILDTAXCREDIT, na.rm=T), 
                  ACDC = mean(ADDITIONALCHILDTAXCREDIT, na.rm=T), ANNUALBENEFITSRECEIVED = mean(ANNUALBENEFITSRECEIVED, na.rm=T),
                  ANNUALBENEFITSELIGIBLEFOR = mean(ANNUALBENEFITSELIGIBLEFOR, na.rm=T), YEAR = unique(YEAR))

y2003AVG <- ddply(y2003, .(FIPSSTATECODE, NUMBERDEPKIDS), summarise, EITC = mean(EARNEDINCOMETAXCREDIT, na.rm=T), CTC = mean(CHILDTAXCREDIT, na.rm=T), 
                  ACDC = mean(ADDITIONALCHILDTAXCREDIT, na.rm=T), ANNUALBENEFITSRECEIVED = mean(ANNUALBENEFITSRECEIVED, na.rm=T),
                  ANNUALBENEFITSELIGIBLEFOR = mean(ANNUALBENEFITSELIGIBLEFOR, na.rm=T), YEAR = unique(YEAR))

y2004AVG <- ddply(y2004, .(FIPSSTATECODE, NUMBERDEPKIDS), summarise,EITC = mean(EARNEDINCOMETAXCREDIT, na.rm=T), CTC = mean(CHILDTAXCREDIT, na.rm=T), 
                  ACDC = mean(ADDITIONALCHILDTAXCREDIT, na.rm=T), ANNUALBENEFITSRECEIVED = mean(ANNUALBENEFITSRECEIVED, na.rm=T),
                  ANNUALBENEFITSELIGIBLEFOR = mean(ANNUALBENEFITSELIGIBLEFOR, na.rm=T), YEAR = unique(YEAR))

y2005AVG <- ddply(y2005, .(FIPSSTATECODE, NUMBERDEPKIDS), summarise, EITC = mean(EARNEDINCOMETAXCREDIT, na.rm=T), CTC = mean(CHILDTAXCREDIT, na.rm=T), 
                  ACDC = mean(ADDITIONALCHILDTAXCREDIT, na.rm=T), ANNUALBENEFITSRECEIVED = mean(ANNUALBENEFITSRECEIVED, na.rm=T),
                  ANNUALBENEFITSELIGIBLEFOR = mean(ANNUALBENEFITSELIGIBLEFOR, na.rm=T), YEAR = unique(YEAR))

y2006AVG <- ddply(y2006, .(FIPSSTATECODE, NUMBERDEPKIDS), summarise, EITC = mean(EARNEDINCOMETAXCREDIT, na.rm=T), CTC = mean(CHILDTAXCREDIT, na.rm=T), 
                  ACDC = mean(ADDITIONALCHILDTAXCREDIT, na.rm=T), ANNUALBENEFITSRECEIVED = mean(ANNUALBENEFITSRECEIVED, na.rm=T),
                  ANNUALBENEFITSELIGIBLEFOR = mean(ANNUALBENEFITSELIGIBLEFOR, na.rm=T), YEAR = unique(YEAR))

y2007AVG <- ddply(y2007, .(FIPSSTATECODE, NUMBERDEPKIDS), summarise, EITC = mean(EARNEDINCOMETAXCREDIT, na.rm=T), CTC = mean(CHILDTAXCREDIT, na.rm=T), 
                  ACDC = mean(ADDITIONALCHILDTAXCREDIT, na.rm=T), ANNUALBENEFITSRECEIVED = mean(ANNUALBENEFITSRECEIVED, na.rm=T),
                  ANNUALBENEFITSELIGIBLEFOR = mean(ANNUALBENEFITSELIGIBLEFOR, na.rm=T), YEAR = unique(YEAR))

y2008AVG <- ddply(y2008, .(FIPSSTATECODE, NUMBERDEPKIDS), summarise, EITC = mean(EARNEDINCOMETAXCREDIT, na.rm=T), CTC = mean(CHILDTAXCREDIT, na.rm=T), 
                  ACDC = mean(ADDITIONALCHILDTAXCREDIT, na.rm=T), ANNUALBENEFITSRECEIVED = mean(ANNUALBENEFITSRECEIVED, na.rm=T),
                  ANNUALBENEFITSELIGIBLEFOR = mean(ANNUALBENEFITSELIGIBLEFOR, na.rm=T), YEAR = unique(YEAR))

y2001AVG$FIPSSTATECODE <- as.factor(y2001AVG$FIPSSTATECODE)
y2002AVG$FIPSSTATECODE <- as.factor(y2002AVG$FIPSSTATECODE)
y2003AVG$FIPSSTATECODE <- as.factor(y2003AVG$FIPSSTATECODE)
y2004AVG$FIPSSTATECODE <- as.factor(y2004AVG$FIPSSTATECODE)
y2005AVG$FIPSSTATECODE <- as.factor(y2005AVG$FIPSSTATECODE)
y2006AVG$FIPSSTATECODE <- as.factor(y2006AVG$FIPSSTATECODE)
y2007AVG$FIPSSTATECODE <- as.factor(y2007AVG$FIPSSTATECODE)
y2008AVG$FIPSSTATECODE <- as.factor(y2008AVG$FIPSSTATECODE)

df <- join(y2001AVG, y2002AVG, by=c('FIPSSTATECODE', 'NUMBERDEPKIDS'))
df <- join(df, y2003AVG, by=c('FIPSSTATECODE', 'NUMBERDEPKIDS'))


